### ISSUE TITLE
TCPClientInterface edit interface light mode issue

### ISSUE THREAD

**Issue by AutumnSpark1226** [liamcottle/reticulum-meshchat#25]
![Screenshot_20241216_135200](https://github.com/user-attachments/assets/cb03f680-fc5f-47f2-8e36-a744f581afc0)

As you can see the dark mode color scheme is applied for the Target Host input.

**Comment by liamcottle** [comment]
Thanks, good catch! Fixed in d829cb05e0c640eabe3f24f57a6bf3c60df9a972
