### ISSUE TITLE
pre-defined data is not shown

### ISSUE THREAD

**Issue by AutumnSpark1226** [liamcottle/reticulum-meshchat#28]
I noticed that pre-defined values in input fields as well as pre-checked checkboxes don't show their default values.
NomadNet
![Screenshot_20241217_105813](https://github.com/user-attachments/assets/44d0f59b-1b9e-4c32-9991-292eda72a77f)
MeshChat:
![Screenshot_20241217_105755](https://github.com/user-attachments/assets/18ddd7ba-4318-4173-889f-3515febe1739)

**Comment by RFnexus** [comment]
Do you have the Micron for the above output?

**Comment by RFnexus** [comment]
Thanks for mentioning this. For some reason the masked input only works with a space in front. Will work on a fix. Sorry about that.

**Comment by RFnexus** [comment]
When creating the element changing `input.value = p.data;` to `input.setAttribute('value', p.data);`, and using setAttribute for the checked on checkboxes and radios as well seems to resolve this. Not sure why, but it's working now. Submitting PR.

**Comment by liamcottle** [comment]
Closing this as fixed by https://github.com/liamcottle/reticulum-meshchat/pull/32 Please let us know if it's still a problem :)
