### ISSUE TITLE
*Feature - Image compression in meshchat

### ISSUE THREAD

**Issue by Andrew-a-g** [liamcottle/reticulum-meshchat#31]
In testing we noticed sideband will compress an image down from 30kb to around 3kb.  There was a loss of quality etc sure but this will significantly reduce transfer time and will reduce traffic over low bandwidth links so would be a good option to have.

![meshchat](https://github.com/user-attachments/assets/8209bb03-30bb-4dc6-b8ba-ac4126e0de48)
![size-full](https://github.com/user-attachments/assets/5600c08e-8c81-4aeb-8010-d6597132f30f)
![sideband](https://github.com/user-attachments/assets/59bacf5c-c753-4031-8bed-9cb075f25993)

**Comment by liamcottle** [comment]
Thanks for the suggestion! This has been implemented in 6b4034dae9578debc0d62499a68179c5e9f00bc9 and will be available in the next release 😁
